apiVersion: v2
appVersion: 2.1.7
description: A Helm chart for the NATS.io High Speed Cloud Native Distributed Communications Technology.
home: http://github.com/nats-io/k8s
icon: https://nats.io/img/nats-icon-color.png
keywords:
- nats
- messaging
- cncf
maintainers:
- email: wally@nats.io
  name: Waldemar Quevedo
- email: colin@nats.io
  name: Colin Sullivan
name: nats
version: 1.0.3
