{{- if .Values.auth.enabled }}
{{- if eq .Values.auth.resolver.type "memory" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nats.name" . }}-accounts
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "nats.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    {{- if .Values.commonLabels }}
    {{- include "nats.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}      
data:
  accounts.conf: |-
    {{- .Files.Get "accounts.conf" | indent 6 }}
{{- end }}
{{- end }}
