---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "nats.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "nats.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    {{- if .Values.commonLabels }}
    {{- include "nats.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}    
spec:
  selector:
    app: {{ template "nats.name" . }}
  clusterIP: None
  ports:
  - name: client
    port: 4222
  - name: cluster
    port: 6222
  - name: monitor
    port: 8222
  - name: metrics
    port: 7777
  - name: leafnodes
    port: 7422
  - name: gateways
    port: 7522
